server:
  jsp-servlet:
    init-parameters:
      development: true
  port: 8086
  context-path: /cmfz_hjd
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /
  multipart:
    max-file-size: 10MB
    max-request-size: 100MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

